import 'package:flutter/material.dart';

const List<IconData> categoryIcons = [
  Icons.restaurant,
  Icons.local_cafe,
  Icons.fastfood,
  Icons.shopping_cart,
  Icons.directions_bus,
  Icons.subway,
  Icons.local_taxi,
  Icons.directions_car,
  Icons.local_gas_station,
  Icons.home,
  Icons.cleaning_services,
  Icons.lightbulb,
  Icons.water_drop,
  Icons.medical_services,
  Icons.healing,
  Icons.fitness_center,
  Icons.sports_tennis,
  Icons.sports_soccer,
  Icons.movie,
  Icons.music_note,
  Icons.pets,
  Icons.school,
  Icons.work,
  Icons.flight,
  Icons.hotel,
  Icons.celebration,
  Icons.card_giftcard,
  Icons.phone_iphone,
  Icons.computer,
  Icons.wifi,
  Icons.savings,
  Icons.credit_card,
];
